version: '3.9'
services:
  voila:
    image: brestmoor/map-similarity-voila
    ports:
      - "4000:80"
  osm-api:
    image: wiktorn/overpass-api
    environment:
      - OVERPASS_META=yes
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=https://download.geofabrik.de/europe/poland/malopolskie-latest.osm.bz2
      - OVERPASS_RULES_LOAD=10
    volumes:
      - /big/docker/overpass_db_malopolska/:/db
    restart: always