l = ['Act Country Company Approver',
      'Country Finance Director / Manager',
      'Country Managing Director – Managing Director of a Country',
      'Company L1Upload',
      'Global BU Assistant',
      'Global BU Controller',
      'Global BU Controller - Iran',
      'Global BU Editor',
      'Global BU Enterprise Software Legal',
      'Global BU Legal Responsible',
      'Global BU Managing Director',
      'Global BU Marketing & Sales Manager',
      'Global BU Operations Manager',
      'Global BU Reader FCM',
      'Global BU Reader Report',
      'Global BU Risk Manager',
      'Global BU SCM Manager',
      'Global BU Technology Manager',
      'Global Company Assistant',
      'CFO',
      'Global Company Data Administrator',
      'Global Company Lawyer',
      'Global Company Legal and Integrity',
      'Global Company Marketing & Sales Manager',
      'Global Company OPEX Manager',
      'CEO',
      'Global Company Reader FCM Report',
      'Global Company Reader Report',
      'Global Company Risk Manager',
      'Global Company Risk Manager initiator',
      'Global Company Risk Manager Projects',
      'Global Company Risk Review Administrator',
      'Chief Technology Officer (CTO)',
      'CEO',
      'CFO',
      'HBU Controller',
      'HBU Manager',
      'HBU Operations Manager',
      'Lead Company Controller',
      'Lead Company Manager',
      'Local BU Controller',
      'Local BU Editor',
      'Local BU Editor FCM',
      'Local BU Manager',
      'Local BU OPEX Manager',
      'Local BU Reader',
      'Local BU Reader FCM',
      'Local Company Controller',
      'Local Company Editor',
      'Local Company Editor FCM',
      'Local Company Legal Responsible',
      'Local Company Manager',
      'Local Company OPEX Manager',
      'Local Company Reader',
      'Local Company Reader FCM',
      'Local Company Risk Manager',
      'Local Company Sales Manager',
      'Local Company SuperReporter',
      'Local Company Tax Responsible',
      'Local GF-Internal Audit - BU',
      'Local GF-Internal Audit - Company',
      'Region Manager']
