city_sets = [
    ('France north ext', [
        "Dunkerque, France",
        "Calais, France",
        "Arras, France",
        "Hazebrouck, France",
        "Bethune, France",
        "Cambrai, France",
        "Boulogne-sur-mer, France",
        "Abbeville, France",
        "Amiens, France",
        "Saint-Quentin, France",
        "Dieppe, France",
        "Beauvais, France",
        "Clermont, France",
        "Evreux, France",
        "Rouen, France",
        "Compiegne, France",
        "Le Havre, France",
        "Dreux, France",
        "Dives-sur-mer, France",
        "Caen, France",
        "Saint-Lo, France",
        "Bayeux, France",
        "Chartres, France",
        "Alencon, France",
        "Dinan, France",
        "Le Mans, France",
        "Laval, France",
        "Cherbourg-en-Cotentin, France",
        "Rennes, France",
        "Saint-Malo, France",
        "Dinard, France",
        "Saint-Brieuc, France",
        "Guingamp, France",
        "Lannion, France",
        "Morlaix, France",
        "Brest, France",
        "Carhaix-Plouguer, France",
        "Quimper, France",
        "Ploemeur, France",
        "Lorient, France",
        "Lanester, France",
        "Hennebont, France",
        "Auray, France",
        "Vannes, France",
        "Pontivy, France",
        "Ploermel, France", ]),
    ('France South', [
        "Hendaye, France",
        "Saint-Jean-de-Luz, France",
        "Cambo-les-bains, France",
        "Pau, France",
        "Carcassonne, France",
        "Argeles-sur-mer, France",
        "Perpignan, France",
        "Saint-Laurent-de-la-Salanque, France",
        "Narbonne, France",
        "Beziers, France",
        "Agde, France",
        "Sete, France",
        "Frontignan, France",
        "Mauguio, France",
        "Lunel, France",
        "Nimes, France",
        "Marignane, France",
        "Bouc-Bel-Air, France",
        "Aubagne, France",
        "Aix-en-Provence, France",
        "Gardanne, France",
        "Avignon, France",
        "Toulon, France",
        "La Crau, France",
        "Hyeres, France",
        "Saint-Maximin-la-Sainte-Baume, France",
        "Brignoles, France",
        "Sainte-Maxime, France",
        "Frejus, France",
        "Saint-Raphael, France",
        "Draguignan, France",
        "Mandelieu-la-Napoule, France",
        "Cannes, France",
        "Le Cannet, France",
        "Vallauris, France",
        "Antibes, France",
        "Grasse, France",
        "Cagnes-Sur-Mer, France",
        "Saint-Laurent-du-Var, France",
        "Nice, France",
        "Roquebrune-Cap-Martin, France",
        "Menton, France"]),
    ('Italy north', [
        "Lecco, Italy",
        "Valmadrera, Italy",
        "Nembro, Italy",
        "Albino, Italy",
        "Alzano Lombardo, Italy",
        "Clusone, Italy",
        "Pergine Valsugana, Italy",
        "Trento, Italy",
        "Borgo Valsugana, Italy",
        "Feltre, Italy",
        "Maniago, Italy",
        "San Daniele del Friuli, Italy",
        "Udine, Italy",
        "Pordenone, Italy",
        "Oderzo, Italy",
        "Treviso, Italy",
        "Brescia, Italy",
        "Rezzato, Italy",
        "Cremona, Italy",
        "Mantova, Italy",
        "Asti, Italy",
        "Alessandria, Italy",
        "Pavia, Italy",
        "Lodi, Italy",
        "Biella, Italy",
        "Vercelli, Italy",
        "Novara, Italy",
        "Varese, Italy",
        "Como, Italy",
        "Mondovi, Italy",
        "Fossano, Italy",
        "Piacenza, Italy", ]),
    ('Poland-Mountains', [
        "Ustron, Poland",
        "Wisla, Slaskie, Poland",
        "Szczyrk, Poland",
        "Wegierska Gorka, Poland",
        "Zywiec, Poland",
        "Zawoja, Poland",
        "Sucha Beskidzka, Poland",
        "Spytkowice, Nowotarski, Poland",
        "Rabka-Zdroj, Poland",
        "Nowy Targ, Poland",
        "Bialka Tatrzanska, Poland",
        "Bukowina Tatrzanska, Poland",
        "Kluszkowce, Poland",
        "Szczawnica, Poland",
        "Piwniczna-Zdroj, Poland",
        "Kasina Wielka, Poland",
        "Limanowa, Poland",
        "Szaflary, Poland",
        "Ludzmierz, Poland", ]),
    ('Italy Sicily', [
        "Rosolini, Sicily, Italy",
        "Ispica, Sicily, Italy",
        "Pachino, Sicily, Italy",
        "Pozzallo, Sicily, Italy",
        "Scicli, Sicily, Italy",
        "Noto, Sicily, Italy",
        "Avola, Sicily, Italy",
        "Ragusa, Sicily, Italy",
        "Vittoria, Sicily, Italy",
        "Comiso, Sicily, Italy",
        "Gela, Sicily, Italy",
        "Niscemi, Sicily, Italy",
        "Licata, Sicily, Italy",
        "Campobello di Licata, Sicily, Italy",
        "Ravanusa, Sicily, Italy",
        "Canicatti, Sicily, Italy",
        "Riesi, Sicily, Italy",
        "Paterno, Sicily, Italy",
        "Adrano, Sicily, Italy",
        "Biancavilla, Sicily, Italy",
        "Catania, Sicily, Italy",
        "Acireale, Sicily, Italy",
        "Belpasso, Sicily, Italy",
        "Adrano, Sicily, Italy",
        "Palma di Montechiaro, Sicily, Italy",
        "Favara, Sicily, Italy",
        "Sciacca, Sicily, Italy",
        "Castelvetrano, Sicily, Italy",
        "Messina, Sicily, Italy",
        "Siracusa, Sicily, Italy"]),
    ('Germany Ruhr', [
        "Bochum, Germany",
        "Duisburg, Germany",
        "Oberhausen, Germany",
        "Gelsenkirchen, Germany",
        "Hagen, Germany",
        "Hamm, Germany",
        "Herne, Germany",
        "Witten, Germany",
        "Bergkamen, Germany",
        "Hattingen, Germany",
        "Herten, Germany",
        "Recklinghausen, Germany",
        "Moers, Germany",
        "Dorsten, Germany",
        "Dinslaken, Germany",
        "Castrop-Rauxel, Germany",
        "Gladbeck, Germany",
        "Marl, Germany",
        "Mulheim an der Ruhr, Germany"]),
    ('Germany Bavaria', [
        "Regensburg, Germany",
        "Augsburg, Germany",
        "Bamberg, Germany",
        "Wurzburg, Germany",
        "Erlangen, Germany",
        "Ingolstadt, Germany",
        "Furth, Germany",
        "Bayreuth, Germany",
        "Passau, Germany",
        "Landshut, Germany",
        "Kempten, Germany",
        "Straubing, Germany",
        "Memmingen, Germany",
        "Ansbach, Germany",
        "Kaufbeuren, Germany",
        "Aschaffenburg, Germany",
        "Dachau, Germany",
        "Freising, Germany",
        "Schweinfurt, Germany",
        "Rosenheim, Germany",
        "Neu-Ulm, Germany",
        "Hof, Germany",
        "Amberg, Germany",
        "Weiden in der Oberpfalz, Germany"]),
    ('Poland-Shore', [
        "Chlopy, Zachodniopomorskie, Poland",
        "Uniescie, Zachodniopomorskie, Poland",
        "Miedzyzdroje, Zachodniopomorskie, Poland",
        "Dziwnow, Zachodniopomorskie, Poland",
        "Kolobrzeg, Zachodniopomorskie, Poland",
        "Mielno, Zachodniopomorskie, Poland",
        "Darlowo, Zachodniopomorskie, Poland",
        "Grzybowo, Zachodniopomorskie, Poland",
        "Kamien Pomorski, Zachodniopomorskie,  Poland",
        "Gaski, Zachodniopomorskie, Poland",
        "Sarbinowo, Zachodniopomorskie, Poland",
        "Ustka, Pomorskie, Poland",
        "Rowy, Pomorskie, Poland",
        "Leba, Pomorskie, Poland",
        "Puck, Pomorskie, Poland",
        "Jastarnia, Pomorskie, Poland",
        "Krynica Morska, Pomorskie, Poland",
        "Karwia, Pomorskie, Poland",
        "Jastrzebia Gora, Pomorskie, Poland",
        "Chlapowo, Pomorskie, Poland",
        "Hel, Pomorskie, Poland"]),
    ('France-North', [
        "Meaux, France",
        "Coulommiers, France",
        "Compiegne, France",
        "Chauny, France",
        "Soissons, France",
        "Sezanne, France",
        "Troyes, France",
        "Reims, France",
        "Montargis, France",
        "Evreux, France",
        "Beauvais, France",
        "Amiens, France",
        "L'aigle, France",
        "Lisieux, France",
        "Laval, France",
        "Lamballe, France",
        "Saint-Malo, France",
        "Dinan, France",
        "Saint-Brieuc, France",
        "Guingamp, France",
        "Lannion, France",
        "Morlaix, France",
        "Landivisiau, France",
        "Landerneau, France",
        "Chateau-Gontier, France",
        "Angers, France",
        "Nantes, France",
        "Tours, France",
        "La Roche-Sur-Yon, France",
        "Challans, France",
        "Cholet, France",
        "Thouars, France",
        "Niort, France"]),
    ('Russia-West', [
        "Serpukhov, Russia",
        "Obninsk, Russia",
        "Kolomna, Russia",
        "Ryazan, Russia",
        "Tver, Russia",
        "Voronezh, Russia",
        "Stary Oskol, Russia",
        "Belgorod, Russia",
        "Yaroslavl, Russia",
        "Ivanovo, Russia",
        "Pskov, Russia",
        "Veliky Novgorod, Russia",
        "Volgograd, Russia",
        "Saratov, Russia",
        "Engels, Russia",
        "Balakovo, Russia",
        "Penza, Russia",
        "Cheboksary, Russia",
        "Novocheboksarsk, Russia",
        "Yoshkar-Ola, Russia",
        "Vladimir, Russia",
        "Ulyanovsk, Russia",
        "Dimitrovgrad, Russia",
        "Ufa, Russia",
        "Orenburg, Russia"]),
    ('Malopolska-mountains', [
        "Zakopane, Malopolskie, Poland",
        "Szczawnica, Malopolskie, Poland",
        "Piwniczna-Zdroj, Malopolskie, Poland",
        "Krynica-Zdroj, Malopolskie, Poland",
        "Muszyna, Malopolskie, Poland",
        "Stary Sacz, Malopolskie, Poland",
        "Tylicz, Malopolskie, Poland",
        "Szaflary, Malopolskie, Poland",
        "Poronin, Malopolskie, Poland",
        "Czarny Dunajec, Malopolskie, Poland", ]),
    ("Malopolska near Krakow", [
        "Zabierzow, Malopolska, Poland",
        "Modlniczka, Malopolska, Poland",
        "Rzaska, Malopolska, Poland",
        "Balice, Malopolska, Poland",
        "Wegrzce, Malopolska, Poland",
        "Zielonki, Malopolska, Poland",
        "Modlnica, Malopolska, Poland",
        "Kryspinow, Malopolska, Poland",
        "Swoszowice, Malopolska, Poland",
        "Niepolomice, Malopolska, Poland",
        "Skawina, Malopolska, Poland",
        "Swiatniki Gorne, Malopolska, Poland"]),
    ('Russia-West', [
        "Serpukhov, Russia",
        "Obninsk, Russia",
        "Kolomna, Russia",
        "Ryazan, Russia",
        "Tver, Russia",
        "Voronezh, Russia",
        "Stary Oskol, Russia",
        "Belgorod, Russia",
        "Yaroslavl, Russia",
        "Ivanovo, Russia",
        "Pskov, Russia",
        "Veliky Novgorod, Russia",
        "Volgograd, Russia",
        "Saratov, Russia",
        "Engels, Russia",
        "Balakovo, Russia",
        "Penza, Russia",
        "Cheboksary, Russia",
        "Novocheboksarsk, Russia",
        "Yoshkar-Ola, Russia",
        "Vladimir, Russia",
        "Ulyanovsk, Russia",
        "Dimitrovgrad, Russia",
        "Ufa, Russia",
        "Orenburg, Russia", ])
]
